### ISSUE TITLE
swift 1.2 errors

### ISSUE THREAD

**Issue by yavuz** [Haneke/HanekeSwift#171] opened 2015-04-09 20:58 UTC
swift 1.2 causes many errors

**Comment by mohsen1** [comment] 2015-04-11 03:57
+1

**Comment by xiaoxiaocainiao** [comment] 2015-04-11 13:35
+1

**Comment by CWadeCantley** [comment] 2015-04-11 14:48
I just updated to the newest versions of xcode and yes... many many errors.  I working on cleaning it up so that I can use it but there are a couple gotchas that I don't fully understand.  Hopefully the author will jump on them.

**Comment by HerbstLukas** [comment] 2015-04-11 18:37
I'm also working on getting it running with Swift 1.2, but currently I have 5 errors remaining :/ Hope that the author's will get an version ready :( +1

**Comment by yavuz** [comment] 2015-04-11 20:05
may be, you can use it. temporarily :)
https://github.com/akolov/HanekeSwift/tree/swift-1.2

**Comment by shivateja** [comment] 2015-04-12 06:54
+1

**Comment by hpique** [comment] 2015-04-12 13:12
Duplicate of #151.

**Closed by hpique** 2015-04-12 13:12 UTC
Labels: duplicate

**Comment by KMKRN** [comment] 2015-08-09 22:26
There is an issue with JSON data. Fetching JSON data from server seems to return one cached object which is not getting released. Cleaning Xcode cache did nothing.
