### ISSUE TITLE
Is the project still maintained?

### ISSUE THREAD

**Issue by Codeido** [Haneke/HanekeSwift#415] opened 2017-09-06 13:57 UTC
I see too many bugs on issues panel and 15 pull request pending from 2 years. Any news? Is the project still maintained?

**Comment by artemkalinovsky** [comment] 2017-09-13 08:19
Also, I'd like to know about Swift 4 migration

**Comment by dcharbonnier** [comment] 2017-09-20 12:26
There is no PR with a successful build  pending. If someone do the swift 4 migration with no coverage regression I will merge it.

**Comment by Aeon** [comment] 2017-11-28 23:48
@dcharbonnier how about pull request https://github.com/Haneke/HanekeSwift/pull/421? The CI build is failing but the failure seems to be with CI config, not due to error in the code?

**Comment by dcharbonnier** [comment] 2017-11-29 06:31
If you want to send a PR to fix the CI config I will be happy to merge it @Aeon

**Comment by gringoireDM** [comment] 2018-01-18 17:03
+1

Is the project still maintained? The build is failing, PR opened and never merged. I would like to contribute, but I need to see that there is a minimum effort at least to fix the build settings or I will have to consider the project dead and move away from it in my dependencies. I appreciate the work you did so far, but if it is unmaintained please let us know.

**Comment by dcharbonnier** [comment] 2018-01-18 17:20
the answer is still valid @gringoireDM :-)

**Comment by dcharbonnier** [comment] 2018-01-18 17:32
I closed the PR too old with a failing build. I'm not the original developer of this project but I can't merge something with failing tests.
If you want to help you are more than welcome, the first step is to make the build pass with travis (or find an other CI if you want)
In the issues, some are outdated or just questions if someone want to help and reply or mention me when it's something to close, you are welcome :-)

**Comment by dcharbonnier** [comment] 2018-01-24 12:50
the master now support swift 4

**Closed by dcharbonnier** 2018-01-24 12:50 UTC
